language: rust
sudo: false
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
rust:
  - 1.17.0
  - 1.18.0
  - 1.19.0
  - 1.20.0
  - 1.21.0
  - 1.22.0
  - 1.23.0
  - 1.24.0
  - 1.25.0
  - stable
  - beta
  - nightly
# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      cargo run --example main
after_success:
  # measure code coverage and upload to coveralls.io
  - travis-cargo coveralls --no-sudo
matrix:
  allow_failures:
    - rust: nightly
