language: rust
rust:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  - stable
  - beta
  - nightly
script:
  - cargo build
  - cargo test
after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build &&
  cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --include-pattern=src/pinyin --exclude-pattern=/.cargo target/kcov target/debug/pinyin-*
matrix:
  allow_failure:
    - rust: nightly
