[package]
name = "pinyin"
version = "0.1.0"
authors = ["mozillazg <mozillazg101@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mozillazg/rust-pinyin"
repository = "https://github.com/mozillazg/rust-pinyin"
description = "Convert Chinese to pinyin"
documentation = "https://docs.rs/pinyin/"
keywords = ["pinyin", "hanzi", "Chinese", "拼音"]
build = "build.rs"

[features]
unstable = []

[dependencies]
regex = "~0.1.8"
phf = "~0.7.3"

[build-dependencies]
phf_codegen = "~0.7.3"
regex = "~0.1.8"
